name: Get GitHub Comments

on:
  issue_comment:
    types: [created]

jobs:
  OpenAI_Reply:
    if: "contains(github.event.issue.labels.*.name, 'gitalk')"
    runs-on: self-hosted
    permissions:
      issues: write
    steps:
      - name: Get all issue comments
        run: |
          mkdir .github
          wget https://raw.githubusercontent.com/xihajun/image/main/img/ChatAI.py
          COMMENTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments")
          echo "Issue comments: ${COMMENTS}"
          COMMENT_BODY=$(echo ${COMMENTS} | jq '.[-1].body')
          echo -e "Based on the above documents, can you let me know ${COMMENT_BODY}" > comments.txt
          wget $(echo "${{ github.event.issue.body }}" | grep "http://127.0.0.1:8000/" | grep -o '\/[^ ]*' | sed -e 's/\/127.0.0.1:8000\/[^\/]*\///' -e 's/\/$//' -e 's/^/https:\/\/raw.githubusercontent.com\/xihajun\/tmp\/main\/mkdocs\/docs/' -e 's/$/.md/') -O .github/promptdoc.md
          wget https://raw.githubusercontent.com/xihajun/image/main/img/aiDoc.py -O AIreply.py

      - name: run script
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OUTPUTFILE: ".github/comment-template.md"
          BODY: ${{ github.event.comment.body }}
        run: python AIreply.py "$BODY"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          # token: ${{ secrets.PAT }}
          # comment-author: 'github-actions[bot]'
          issue-number: ${{ github.event.issue.number }}
          body-file: '.github/comment-template.md'
