name: Get GitHub Comments

on:
  issue_comment:
    types: [created]

jobs:
  OpenAI_Reply:
    if: "contains(github.event.issue.labels.*.name, 'gitalk')"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install openai
          
      - name: Get all issue comments
        run: |
          mkdir .github
          wget https://raw.githubusercontent.com/xihajun/image/main/img/ChatAI.py
          COMMENTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments")
          echo "Issue comments: ${COMMENTS}"
          COMMENT_BODY=$(echo ${COMMENTS} | jq '.[-1].body')
          echo -e "${COMMENT_BODY}" #> comments.txt
