name: Get GitHub Comments

on:
  issue_comment:
    types: [created]

jobs:
  OpenAI_Reply:
    if: "contains(github.event.issue.labels.*.name, 'gitalk')"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install openai
          
      - name: Get all issue comments
        run: |
          mkdir .github
          wget https://raw.githubusercontent.com/xihajun/image/main/img/ChatAI.py
          COMMENTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments")
          echo "Issue comments: ${COMMENTS}"
          COMMENT_BODY=$(echo ${COMMENTS} | jq '.[-1].body')
          echo -e "${COMMENT_BODY}" #> comments.txt
          echo ${{github.event.issue.labels.*.name}}
          LABELS=$(curl -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels)
          LABELS_=$(echo ${LABELS} | jq '.[-1].body')
          echo -e "${LABELS_}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Get Issue Body
        uses: actions/get-issue-body@master
        with:
          issue_number: ${{github.event.issue.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Link From Body
        run: echo $(echo "${{ steps.get_body.outputs.body }}" | grep -oP '(?<=\()[^\)]+(?=\))')
